# Generated by Django 5.0.4 on 2024-04-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learningprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='CertificationProcess',
        ),
        migrations.DeleteModel(
            name='CourseMaterial',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='LearningProgress',
        ),
    ]
