# Generated by Django 5.0.4 on 2024-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_role'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('intern', 'Стажер'), ('barista', 'Бариста'), ('manager', 'Менеджер'), ('supervisor', 'Управляющий'), ('hr_manager', 'Менеджер по персоналу')], max_length=20, unique=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
