# Generated by Django 5.0.4 on 2024-04-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_role_userprofile_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('intern', 'Стажер'), ('barista', 'Бариста'), ('manager', 'Менеджер'), ('supervisor', 'Управляющий'), ('hr_manager', 'Менеджер по персоналу')], default='intern', max_length=20),
        ),
    ]
