# Generated by Django 5.0.4 on 2024-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
