# Generated by Django 5.0.4 on 2024-04-04 18:41

import courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('employees', '0002_role_userprofile_delete_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='role',
            field=models.ForeignKey(default=courses.models.get_hr_manager_role_id, on_delete=django.db.models.deletion.CASCADE, to='employees.role'),
        ),
    ]
