# Generated by Django 5.0.4 on 2024-04-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('intern', 'Intern'), ('barista', 'Barista'), ('manager', 'Manager'), ('hr_manager', 'HrManager'), ('supervisor', 'Supervisor')], default='hr_manager', max_length=100),
        ),
    ]
