# Generated by Django 5.0.4 on 2024-04-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty',
        ),
    ]
