# Generated by Django 5.0.4 on 2024-04-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_course_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='role',
            field=models.CharField(choices=[('intern', 'Intern'), ('barista', 'Barista'), ('manager', 'Manager'), ('hr_manager', 'HrManager'), ('supervisor', 'Supervisor')], default='hr_manager', max_length=100),
        ),
    ]
