# Generated by Django 5.0.4 on 2024-04-06 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='role',
        ),
    ]
