# Generated by Django 5.0.4 on 2024-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_certificationprocess_coursematerial_grade_and_more'),
        ('employees', '0005_delete_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='site_url',
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='learningprogress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user', 'course')},
        ),
    ]
