# Generated by Django 5.0.4 on 2024-04-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_coursematerial_material_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningprogress',
            old_name='completed',
            new_name='is_complete',
        ),
        migrations.RemoveField(
            model_name='certificationprocess',
            name='certification_result',
        ),
    ]
