# Generated by Django 5.0.4 on 2024-04-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_completed_learningprogress_is_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
