# Generated by Django 5.0.4 on 2024-04-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_slug_remove_lecture_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(default='', max_length=100),
        ),
    ]
