# Generated by Django 5.0.4 on 2024-04-08 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_alter_course_course_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_slug',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_slug',
        ),
    ]
