# Generated by Django 5.0.4 on 2024-04-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_lecture_lecture_slug_test_test_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
