# Generated by Django 5.0.4 on 2024-04-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_grade_test'),
        ('employees', '0006_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('user', 'test')},
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
    ]
