# Generated by Django 5.0.4 on 2024-04-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_grade_unique_together_remove_grade_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseMaterial',
            new_name='LectureMaterial',
        ),
    ]
